/* Executor: It is responsible for implementing the core functionality of this assignment, that is:
    1. Dynamically allocating and de-allocating a random sized array for each iteration.
    2. Populating elements in the array with random characters.
    3. Counting the number of vowels and consonants in the array.
    4. Computing the ratio vowels/consonants.
    5. Track the iteration with maximum number of vowels in the array.
    6. Obtaining the average value of vowels/consonants for all iterations and returning to Starter and printing the iteration number with maximum vowels in the array.
*/

#include <stdio.h>
#include <stdlib.h>

// This function takes in a random value generated by rand() and returns a value between 50 (inclusive)
// and 100 (exclusive), which should be used as the number of iterations.
int get_iteration_no(int rand)
{
    return ((rand % (100 - 50) + 50));
}

// This function takes in a random value generated by rand() and returns a value between 100 (inclusive)
// and 150 (exclusive), which should be used as the array size for the array in one iteration.
// This function should be called once for each iteration.
int get_arr_size(int rand)
{
    return ((rand % (150 - 100) + 100));
}

// This function takes in a random value generated by rand() and generates a value between 65 (inclusive)
// and 90 (inclusive), which is then explicitly converted into a character and returned to the calling function.
// This assignment uses only upper case characters.
char get_arr_val(int rand)
{
    int rndNum = ((rand % (90 - 65 + 1) + 65));
    char rndChar = (char)rndNum;
    return rndChar;
}

/*
    This function takes the populated array, it’s size and the address to maxCount variable used in
    get_running_ratio(). It then counts the number of vowels and consonants, and returns the ratio of
    vowels/consonants. Also, it checks if the current value in address pointed by maxCountPointer is lesser
    than count of vowels in the current array (it means that the maximum number of vowels found in iterations
    so far is less than the current iteration). If yes, then it places the value of count in the address pointed
    by maxCountPointer.
*/
float ratio(char *arr, int size, int *maxCountPointer)
{
    // count # vowels & consonants
    int countVowel = 0;
    int countCons = 0;
    for (size_t i = 0; i < size; i++)
    {
        if ((arr[i] == 'A') || (arr[i] == 'E') || (arr[i] == 'I') || (arr[i] == 'O') || (arr[i] == 'U'))
        {
            countVowel++;
        }
        else
        {
            countCons++;
        }
    }

    /* check if curr value in address is pointed by maxCountPoiter < count of vowels in current array
        (max num of vowels found in iterations is less than current iteration)
        if yes, put the value of count in address pointed by maxCountPointer
    */
    if (*maxCountPointer < countVowel)
    {
        *maxCountPointer = countVowel;
    }

    // returning the final calculated ratio of vowels:consonants
    return ((float)countVowel / (float)countCons);
}

double get_running_ratio()
{
    int maxCount = 0;     // max num of vowels in array
    int maxIteration = 0; // iteration num that array belongs to
    float sumRatios = 0;  // to calculate overall average in step 7

    int numAllocations = get_iteration_no(rand());

    for (int i = 0; i < numAllocations; i++)
    {
        /* steps 3 - 8
            Each time through the loop you will be filling a randomly sized array (step 3)
            with random characters (step 4)
            and get a ratio of vowels to consonants (step 6) for each.
        */

        // step 3
        int arrSize = get_arr_size(rand());
        char *strArr = (char *)malloc(sizeof(char) * arrSize);

        // step 4
        for (int j = 0; j < arrSize; j++)
        {
            strArr[j] = get_arr_val(rand());
        }

        // steps 5 & 6
        int tmpMaxCount = maxCount;

        // dynamically allocating memory on the heap
        float calcRatio = ratio(strArr, arrSize, &maxCount);

        if (tmpMaxCount != maxCount)
        {
            maxIteration = i + 1;
        }

        // getting the sum of the calculated ratios
        sumRatios += calcRatio;

        // freeing memory
        free(strArr);
    }

    // step 7
    float avgRatio = sumRatios / numAllocations;

    printf("[Executor]: Number of iterations is  %d\n", numAllocations);
    printf("[Executor]: Iteration with maximum vowel count is  %d\n", maxIteration);

    return (double)avgRatio;
}