FILES = Buffer.java Consumer.java Coordinator.java Producer.java
SUBMIT_EXE = HW5

all:
	javac $(FILES)
run:
	Java Coordinator
clean:
	rm *.class
package:
	tar cvzf $(SUBMIT_EXE).tar $(FILES) Makefile